### ISSUE TITLE
Date Box Label Inconsistencies

### ISSUE THREAD

**Issue by nkrogstad** [SerSports/SerSports-Project#14]
While transitioning through the different screens I noticed some of the date box labels read "Date" as opposed to "YYYY-MM-DD". Since the latter is the required format it would be easier for the user if they all were labeled that.

**Comment by gtikhono** [comment]
https://github.com/SerSports/SerSports-Project/commit/22bc916d712f4c3fc616ac98f333bb30e04c00c7
